"use strict";

/* istanbul ignore file */

/* global ace */
ace.define('ace/theme/cucumber', ['require', 'exports', 'module', 'ace/lib/dom'], function (acequire, exports) {
  exports.isDark = false;
  exports.cssClass = 'ace-cucumber';
  exports.cssText = "\n.ace-cucumber .ace_gutter {\n  background: #f6f6f6;\n  color: #4D4D4C;\n}\n.ace-cucumber .ace_print-margin {\n  width: 1px;\n  background: #f6f6f6;\n}\n.ace-cucumber {\n  background-color: #FFFFFF;\n  color: #4D4D4C;\n}\n.ace-cucumber .ace_cursor {\n  color: #AEAFAD;\n}\n.ace-cucumber .ace_marker-layer .ace_selection {\n  background: #D6D6D6;\n}\n.ace-cucumber.ace_multiselect .ace_selection.ace_start {\n  box-shadow: 0 0 3px 0px #FFFFFF;\n}\n.ace-cucumber .ace_marker-layer .ace_step {\n  background: rgb(255, 255, 0);\n}\n.ace-cucumber .ace_marker-layer .ace_bracket {\n  margin: -1px 0 0 -1px;\n  border: 1px solid #D1D1D1;\n}\n.ace-cucumber .ace_marker-layer .ace_active-line {\n  background: #EFEFEF;\n}\n.ace-cucumber .ace_gutter-active-line {\n  background-color : #dcdcdc;\n}\n.ace-cucumber .ace_marker-layer .ace_selected-word {\n  border: 1px solid #D6D6D6;\n}\n.ace-cucumber .ace_invisible {\n  color: #D1D1D1;\n}\n.ace-cucumber .ace_keyword,\n.ace-cucumber .ace_meta,\n.ace-cucumber .ace_storage,\n.ace-cucumber .ace_storage.ace_type,\n.ace-cucumber .ace_support.ace_type {\n  color: rgb(25, 144, 184);\n  font-weight: bold;\n}\n.ace-cucumber .ace_keyword.ace_operator {\n  color: #3E999F;\n}\n.ace-cucumber .ace_constant.ace_character,\n.ace-cucumber .ace_constant.ace_language,\n.ace-cucumber .ace_constant.ace_numeric,\n.ace-cucumber .ace_keyword.ace_other.ace_unit,\n.ace-cucumber .ace_support.ace_constant,\n.ace-cucumber .ace_variable.ace_parameter {\n  color: #F5871F;\n}\n.ace-cucumber .ace_constant.ace_other {\n  color: #666969;\n}\n.ace-cucumber .ace_invalid {\n  color: #FFFFFF;\n  background-color: #C82829;\n}\n.ace-cucumber .ace_invalid.ace_deprecated {\n  color: #FFFFFF;\n  background-color: #8959A8;\n}\n.ace-cucumber .ace_fold {\n  background-color: #4271AE;\n  border-color: #4D4D4C;\n}\n.ace-cucumber .ace_entity.ace_name.ace_function,\n.ace-cucumber .ace_support.ace_function,\n.ace-cucumber .ace_variable {\n  color: #4271AE;\n}\n.ace-cucumber .ace_support.ace_class,\n.ace-cucumber .ace_support.ace_type {\n  color: #C99E00;\n}\n.ace-cucumber .ace_heading,\n.ace-cucumber .ace_markup.ace_heading,\n.ace-cucumber .ace_string {\n  color: rgb(47, 156, 10);\n}\n.ace-cucumber .ace_entity.ace_name.ace_tag,\n.ace-cucumber .ace_entity.ace_other.ace_attribute-name,\n.ace-cucumber .ace_meta.ace_tag,\n.ace-cucumber .ace_string.ace_regexp,\n.ace-cucumber .ace_variable {\n  color: #C82829;\n}\n\n.ace-cucumber .ace_argument {\n  color: rgb(166, 127, 89);\n}\n.ace-cucumber .ace_comment {\n  color: rgb(125, 139, 153);\n}\n.ace-cucumber .ace_indent-guide {\n  background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAACCAYAAACZgbYnAAAAE0lEQVQImWP4////f4bdu3f/BwAlfgctduB85QAAAABJRU5ErkJggg==) right repeat-y;\n}\n.ace-cucumber .ace_tooltip {\n  max-width: 400px;\n  white-space: pre-wrap;\n  overflow-wrap: break-word;\n  word-wrap: break-word;\n}";
  const dom = acequire('../lib/dom');
  dom.importCssString(exports.cssText, exports.cssClass);
});