name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Use Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.x'

      - name: Cache node modules
        uses: actions/cache@v2.1.7
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Run yarn
        run: yarn --frozen-lockfile

      - name: Run yarn lint
        run: yarn lint

      - name: Run yarn test
        run: yarn test
